# Generated by Django 4.2 on 2025-07-13 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='current_balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_ammount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=100)),
                ('ammount', models.FloatField(default=0)),
                ('description', models.CharField(max_length=1000)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('current_ammount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp_app.current_balance')),
            ],
        ),
        migrations.DeleteModel(
            name='contact',
        ),
    ]
