# Generated by Django 4.2 on 2025-07-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0004_alter_tracker_ammount_alter_tracker_current_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='created_at',
            field=models.TimeField(auto_now=True),
        ),
    ]
