# Generated by Django 4.2 on 2025-07-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0005_alter_tracker_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
