# Generated by Django 4.2 on 2025-07-15 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
